### ISSUE TITLE
the .gitignore is not correct

### ISSUE THREAD

**Issue by snylonue** [IgnorantCopy/TowerDefence#1]
1. It ignores prebuilt libraries in the bundled `cocos2d`, preventing compilation on other developers' machines.
2. `cmake-build-debug`, which is the working directory of cmake and cannot be reused on other machines, is not ignored.

**Comment by IgnorantCopy** [comment]
![image](https://github.com/user-attachments/assets/2bf8d7cb-78c0-4569-8f15-5b2ef20350f9)
So I should remove '*.lib' and add 'cmake-build-debug', right?

**Comment by snylonue** [comment]
Yes, and note that cmake-build-debug needs to be removed in git.

I recommend to re-initialize the project and do a force push with necessary files.
